FROM artifactory.runc.info/docker/python:3.10-slim-bookworm

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY log_generator.py .

CMD ["python", "log_generator.py"]